In [1]:
import numpy as np

In [6]:
#数组
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])

#全0数组:zeros
zeros = np.zeros((3,4))
#全1数组：ones
ones = np.ones((2,3))
#未初始化数组：empty
empty = np.empty((2,2))
#类似range的数组:arrange
arange = np.arange(10)
#等间隔数组:linespace

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim) #维度：ndim
print(arr.shape) #形状
print(arr.size) #元素总数
print(arr.dtype) #数据类型
print(arr.itemsize) #每个元素字节的大小

2
(2, 3)
6
int32
4


In [9]:
arr = np.array([0, 1, 2, 3, 4, 5])

print(arr[2])      # 索引 → 2
print(arr[1:4])    # 切片 → [1 2 3]
print(arr[::2])    # 步长 → [0 2 4]

# 多维数组索引
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[1, 2])  # → 6
print(arr2d[:, 1])  # 所有行的第2列 → [2 5]

2
[1 2 3]
[0 2 4]
6
[2 5]


In [10]:
arr = np.arange(6)
#(行，列)
print(arr.reshape(2, 3))  # 改变形状
print(arr.flatten())      # 展平为一维
print(arr.T)              # 转置

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # 逐元素相加 → [5 7 9]
print(a * b)   # 逐元素相乘 → [4 10 18]
print(a @ b)   # 点积 → 32
print(np.dot(a, b))  # 同上

[5 7 9]
[ 4 10 18]
32
32


In [12]:
arr = np.array([1.1, 2.2, 3.3])

print(np.sqrt(arr))    # 平方根
print(np.exp(arr))    # 指数
print(np.sin(arr))    # 正弦
print(np.log(arr))    # 自然对数
print(np.round(arr))  # 四舍五入 → [1. 2. 3.] 小数部分去掉，但是还是有小数点

[1.04880885 1.4832397  1.81659021]
[ 3.00416602  9.0250135  27.11263892]
[ 0.89120736  0.8084964  -0.15774569]
[0.09531018 0.78845736 1.19392247]
[1. 2. 3.]


In [13]:
arr = np.array([[1, 2], [3, 4]])

print(np.sum(arr))       # 总和 → 10
print(np.mean(arr))      # 平均值 → 2.5
print(np.max(arr))       # 最大值 → 4
print(np.min(arr))       # 最小值 → 1
print(np.std(arr))       # 标准差
print(np.var(arr))       # 方差
print(np.median(arr))    # 中位数
print(np.percentile(arr, 50))  # 百分位数

10
2.5
4
1
1.118033988749895
1.25
2.5
2.5


In [14]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.matmul(a, b))  # 矩阵乘法
print(np.linalg.inv(a))  # 矩阵求逆
print(np.linalg.det(a))  # 行列式
print(np.linalg.eig(a))  # 特征值和特征向量

[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [15]:
# 设置随机种子
np.random.seed(42)

# 生成随机数
print(np.random.rand(3))       # [0,1)均匀分布
print(np.random.randn(3))      # 标准正态分布
print(np.random.randint(0, 10, size=5))  # 整数随机数
print(np.random.normal(0, 1, 10))  # 正态分布

[0.37454012 0.95071431 0.73199394]
[-1.11188012  0.31890218  0.27904129]
[7 2 5 4 1]
[ 1.01051528  0.23309524  0.11799461  1.46237812  1.53871497 -2.43910582
  0.60344123 -0.25104397 -0.16386712 -1.47632969]


In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 拼接
print(np.concatenate([a, b]))  # [1 2 3 4 5 6]
print(np.vstack([a, b]))      # 垂直堆叠
print(np.hstack([a, b]))      # 水平堆叠

# 分割
arr = np.arange(9).reshape(3, 3)
print(np.split(arr, 3))       # 均等分割
print(np.vsplit(arr, 3))      # 垂直分割
print(np.hsplit(arr, 3))      # 水平分割

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
